name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - run: npm install
    - run: npm run package
    - run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
